channels:
  - pytorch
  - nvidia/label/cuda-11.8.0
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - cxx-compiler
  - cuda-toolkit
  - cuda-compiler
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - xclip
  - git
  - nodejs
  - pytorch
  - torchvision
  - pip
  - pip:
    # - mambavision
    - optuna
    - ray[tune]
    - redis
    - scikit-learn
    - h5py
    - tqdm
    - pandas
    - ftfy
    - regex
    - fsspec
    - huggingface_hub
    - transformers[sentencepiece]
    - braceexpand
    - kaggle
    - accelerate
    - open_clip_torch

